import React, { useState } from 'react';
import {
  BarChart3,
  Download,
  FileSpreadsheet,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Layers,
  ShieldCheck,
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useAuth } from '../context/AuthContext';

export const ReportsView = ({ complaints = [], departmentData = null }) => {
  const { user } = useAuth();
  const [downloadingCSV, setDownloadingCSV] = useState(false);
  const [downloadingPDF, setDownloadingPDF] = useState(false);

  // Compute key summary metrics for reports
  const totalNC = complaints.length;
  const openCount = complaints.filter(
    (c) => c.status === 'Open' || c.status === 'Assigned' || c.status === 'In Progress'
  ).length;
  const overdueCount = complaints.filter((c) => {
    if (c.status === 'Closed') return false;
    return c.deadlineTimestamp && Date.now() > new Date(c.deadlineTimestamp).getTime();
  }).length;
  const closedCount = complaints.filter((c) => c.status === 'Closed').length;
  const slaRate = totalNC > 0 ? Math.round(((totalNC - overdueCount) / totalNC) * 100) : 100;

  // 1. PDF Export Handler (Native .pdf document download)
  const handleExportPDF = () => {
    setDownloadingPDF(true);
    try {
      const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'pt',
        format: 'a4',
      });

      const primaryColor = [37, 99, 235]; // Indigo / Royal Blue
      const darkColor = [15, 23, 42]; // Slate 900
      const mutedColor = [100, 116, 139]; // Slate 500

      // Top Banner
      doc.setFillColor(...primaryColor);
      doc.rect(0, 0, doc.internal.pageSize.getWidth(), 45, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(15);
      doc.setTextColor(255, 255, 255);
      doc.text('GARMENT QUALITY MANAGEMENT SYSTEM (QMS)', 40, 28);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(
        'Unit #4 • ISO 9001:2015 & Buyer Compliance Register',
        doc.internal.pageSize.getWidth() - 40,
        28,
        { align: 'right' }
      );

      // Report Header Section
      const generatedAt = new Date().toLocaleString();
      doc.setTextColor(...darkColor);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Official Non-Conformance & Defect Audit Report', 40, 74);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...mutedColor);
      const userText = user
        ? `Generated By: ${user.name} (${user.employeeId || 'N/A'}) • ${user.department || 'Quality Assurance'}`
        : 'Generated By: System Administrator';
      doc.text(`${userText}   |   Generated Date: ${generatedAt}`, 40, 90);

      // KPI Summary Banner Box
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(40, 102, doc.internal.pageSize.getWidth() - 80, 42, 6, 6, 'FD');

      const boxWidth = (doc.internal.pageSize.getWidth() - 80) / 5;
      const metrics = [
        { label: 'Total Defects', value: String(totalNC), color: [15, 23, 42] },
        { label: 'Open / Pending', value: String(openCount), color: [217, 119, 6] },
        { label: 'Overdue SLA', value: String(overdueCount), color: [225, 29, 72] },
        { label: 'Closed / Verified', value: String(closedCount), color: [16, 185, 129] },
        { label: 'SLA Adherence', value: `${slaRate}%`, color: [79, 70, 229] },
      ];

      metrics.forEach((m, idx) => {
        const x = 40 + idx * boxWidth + boxWidth / 2;
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...mutedColor);
        doc.text(m.label, x, 118, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...m.color);
        doc.text(m.value, x, 134, { align: 'center' });
      });

      // Prepare Table Data
      const headers = [
        ['NC ID', 'Finding / Description', 'Department', 'Severity', 'Assigned To', 'Due Date', 'Status', 'CAP Status'],
      ];

      const tableData = complaints.map((c) => [
        c.complaintId || 'NC-N/A',
        (c.title || c.describeFinding || 'Untitled Defect').slice(0, 42),
        c.department || 'N/A',
        c.priority || 'Medium',
        c.assignedTo?.name || 'Unassigned',
        c.deadlineTimestamp ? new Date(c.deadlineTimestamp).toLocaleDateString() : 'N/A',
        c.status || 'Open',
        c.cap?.status || (c.capRequired ? 'Required' : 'None'),
      ]);

      autoTable(doc, {
        head: headers,
        body: tableData,
        startY: 154,
        margin: { left: 40, right: 40, bottom: 40 },
        theme: 'striped',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: [255, 255, 255],
          fontSize: 8,
          fontStyle: 'bold',
          halign: 'left',
        },
        styles: {
          fontSize: 8,
          cellPadding: 5,
          overflow: 'linebreak',
        },
        columnStyles: {
          0: { cellWidth: 72, fontStyle: 'bold' },
          1: { cellWidth: 'auto' },
          2: { cellWidth: 75 },
          3: { cellWidth: 60 },
          4: { cellWidth: 85 },
          5: { cellWidth: 70 },
          6: { cellWidth: 65 },
          7: { cellWidth: 65 },
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252],
        },
        didDrawPage: (data) => {
          const pageCount = doc.internal.getNumberOfPages();
          doc.setFontSize(8);
          doc.setTextColor(...mutedColor);
          doc.text(
            `Page ${data.pageNumber} of ${pageCount} • Confidential Factory Audit Report • Textile & Garment QMS`,
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() - 18,
            { align: 'center' }
          );
        },
      });

      const filename = `Garment_Compliance_NC_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error('Failed to export PDF report:', err);
    } finally {
      setTimeout(() => setDownloadingPDF(false), 600);
    }
  };

  // 2. CSV Export Handler (Native .csv spreadsheet download)
  const handleExportCSV = () => {
    setDownloadingCSV(true);
    try {
      const headers = [
        'NC Number',
        'Title',
        'Department',
        'Category',
        'Severity',
        'Status',
        'Deadline Condition',
        'Created Date',
        'Due Date',
        'Assigned Person',
        'Assigned Employee ID',
        'CAP Status',
        'Root Cause',
        'Corrective Action',
      ];

      const rows = complaints.map((c) => [
        `"${c.complaintId || ''}"`,
        `"${(c.title || c.describeFinding || '').replace(/"/g, '""')}"`,
        `"${c.department || ''}"`,
        `"${c.category || ''}"`,
        `"${c.priority || ''}"`,
        `"${c.status || ''}"`,
        `"${c.deadlineCondition || ''}"`,
        `"${c.createdAt ? new Date(c.createdAt).toLocaleDateString() : ''}"`,
        `"${c.deadlineTimestamp ? new Date(c.deadlineTimestamp).toLocaleDateString() : ''}"`,
        `"${(c.assignedTo?.name || '').replace(/"/g, '""')}"`,
        `"${c.assignedTo?.employeeId || ''}"`,
        `"${c.cap?.status || (c.capRequired ? 'Required' : 'None')}"`,
        `"${(c.actionTaken?.rootCause || '').replace(/"/g, '""')}"`,
        `"${(c.actionTaken?.correctiveAction || '').replace(/"/g, '""')}"`,
      ]);

      const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      link.setAttribute(
        'download',
        `Garment_Compliance_NC_Report_${new Date().toISOString().slice(0, 10)}.csv`
      );
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Failed to export CSV report:', err);
    } finally {
      setTimeout(() => setDownloadingCSV(false), 600);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Header Banner */}
      <div className="p-5 sm:p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-cyan-400">
              <BarChart3 className="w-4 h-4" />
            </span>
            <h1 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white">
              Compliance Reports & Audit Downloads
            </h1>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Download official quality non-conformance records in PDF document or CSV spreadsheet format.
          </p>
        </div>

        {/* Top Direct Download Actions */}
        <div className="flex items-center gap-2.5">
          {/* Download PDF Button */}
          <button
            type="button"
            id="btn-download-pdf-top"
            onClick={handleExportPDF}
            disabled={downloadingPDF}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs shadow-md shadow-rose-600/20 active:scale-95 transition-all cursor-pointer disabled:opacity-50"
            title="Download formatted PDF Audit Report"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>{downloadingPDF ? 'Generating PDF...' : 'Download PDF Report'}</span>
          </button>

          {/* Download CSV Button */}
          <button
            type="button"
            id="btn-download-csv-top"
            onClick={handleExportCSV}
            disabled={downloadingCSV}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-md shadow-emerald-600/20 active:scale-95 transition-all cursor-pointer disabled:opacity-50"
            title="Download full CSV Defect Register"
          >
            <FileSpreadsheet className="w-3.5 h-3.5" />
            <span>{downloadingCSV ? 'Exporting CSV...' : 'Download CSV Report'}</span>
          </button>
        </div>
      </div>

      {/* KPI Overview Pills */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-2xs">
          <div className="flex items-center justify-between text-slate-500 text-[11px] font-semibold mb-1">
            <span>Total NCs</span>
            <Layers className="w-3.5 h-3.5 text-indigo-500" />
          </div>
          <div className="text-xl font-bold text-slate-900 dark:text-white font-mono">{totalNC}</div>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-2xs">
          <div className="flex items-center justify-between text-slate-500 text-[11px] font-semibold mb-1">
            <span>Open Defects</span>
            <Clock className="w-3.5 h-3.5 text-amber-500" />
          </div>
          <div className="text-xl font-bold text-amber-600 dark:text-amber-400 font-mono">{openCount}</div>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-2xs">
          <div className="flex items-center justify-between text-slate-500 text-[11px] font-semibold mb-1">
            <span>Overdue NCs</span>
            <AlertTriangle className="w-3.5 h-3.5 text-rose-500" />
          </div>
          <div className="text-xl font-bold text-rose-600 dark:text-rose-400 font-mono">{overdueCount}</div>
        </div>

        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-2xs">
          <div className="flex items-center justify-between text-slate-500 text-[11px] font-semibold mb-1">
            <span>SLA Compliance</span>
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" />
          </div>
          <div className="text-xl font-bold text-emerald-600 dark:text-emerald-400 font-mono">{slaRate}%</div>
        </div>
      </div>

      {/* Available Report Formats Grid (Only PDF and CSV) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Format 1: PDF Document Report */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-xs flex flex-col justify-between hover:border-rose-300 dark:hover:border-rose-800 transition-all">
          <div>
            <div className="flex items-center justify-between mb-4">
              <div className="w-11 h-11 rounded-2xl bg-rose-50 dark:bg-rose-950/60 text-rose-600 dark:text-rose-400 flex items-center justify-center shadow-xs">
                <FileText className="w-5 h-5" />
              </div>
              <span className="px-2.5 py-1 rounded-full text-[10px] font-mono font-bold tracking-wider uppercase bg-rose-50 dark:bg-rose-950 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800">
                PDF Document
              </span>
            </div>

            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Official Quality Audit Report (PDF)
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed">
              Standardized non-conformance audit document with official header, executive KPI performance
              metrics, SLA adherence indicators, and structured defect records. Optimized for ISO 9001 audits,
              buyer compliance reviews, and executive sharing.
            </p>

            <div className="mt-4 pt-4 border-t border-slate-100 dark:border-slate-800/80 flex items-center gap-3 text-[11px] text-slate-500 font-medium">
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Executive Metrics
              </span>
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Landscape A4
              </span>
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Page Numbers
              </span>
            </div>
          </div>

          <button
            type="button"
            id="btn-download-pdf-card"
            onClick={handleExportPDF}
            disabled={downloadingPDF}
            className="mt-6 w-full py-2.5 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-md shadow-rose-600/20 active:scale-[0.99] transition-all cursor-pointer disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{downloadingPDF ? 'Generating PDF...' : 'Download PDF Report (.pdf)'}</span>
          </button>
        </div>

        {/* Format 2: CSV Spreadsheet Report */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 shadow-xs flex flex-col justify-between hover:border-emerald-300 dark:hover:border-emerald-800 transition-all">
          <div>
            <div className="flex items-center justify-between mb-4">
              <div className="w-11 h-11 rounded-2xl bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center shadow-xs">
                <FileSpreadsheet className="w-5 h-5" />
              </div>
              <span className="px-2.5 py-1 rounded-full text-[10px] font-mono font-bold tracking-wider uppercase bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                CSV Spreadsheet
              </span>
            </div>

            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Complete Defect Register (CSV)
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-2 leading-relaxed">
              Full tabular defect dataset containing all {complaints.length} non-conformances with full attributes:
              finding descriptions, root causes, corrective action plans, departmental line assignments, due dates,
              and SLA conditions. Fully compatible with Microsoft Excel and Google Sheets.
            </p>

            <div className="mt-4 pt-4 border-t border-slate-100 dark:border-slate-800/80 flex items-center gap-3 text-[11px] text-slate-500 font-medium">
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Excel Compatible
              </span>
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Root Cause Data
              </span>
              <span className="flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> All Columns
              </span>
            </div>
          </div>

          <button
            type="button"
            id="btn-download-csv-card"
            onClick={handleExportCSV}
            disabled={downloadingCSV}
            className="mt-6 w-full py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-md shadow-emerald-600/20 active:scale-[0.99] transition-all cursor-pointer disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{downloadingCSV ? 'Exporting CSV...' : 'Download CSV Register (.csv)'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReportsView;
